// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ArchiveRun(arg1, arg2, arg3) {
  return window['go']['main']['App']['ArchiveRun'](arg1, arg2, arg3);
}

export function ArchiveRunAuto(arg1, arg2) {
  return window['go']['main']['App']['ArchiveRunAuto'](arg1, arg2);
}

export function BringToFront() {
  return window['go']['main']['App']['BringToFront']();
}

export function CancelRun() {
  return window['go']['main']['App']['CancelRun']();
}

export function ClearSessionPasswords() {
  return window['go']['main']['App']['ClearSessionPasswords']();
}

export function DeleteQuery(arg1) {
  return window['go']['main']['App']['DeleteQuery'](arg1);
}

export function DetectEnvironment() {
  return window['go']['main']['App']['DetectEnvironment']();
}

export function Emit(arg1, arg2) {
  return window['go']['main']['App']['Emit'](arg1, arg2);
}

export function ExportQueries() {
  return window['go']['main']['App']['ExportQueries']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function HasSessionPassword(arg1) {
  return window['go']['main']['App']['HasSessionPassword'](arg1);
}

export function ImportQueries(arg1) {
  return window['go']['main']['App']['ImportQueries'](arg1);
}

export function IsRunning() {
  return window['go']['main']['App']['IsRunning']();
}

export function IsSystemDark() {
  return window['go']['main']['App']['IsSystemDark']();
}

export function ListQueries() {
  return window['go']['main']['App']['ListQueries']();
}

export function MoveQuery(arg1, arg2) {
  return window['go']['main']['App']['MoveQuery'](arg1, arg2);
}

export function OpenRunFolder(arg1) {
  return window['go']['main']['App']['OpenRunFolder'](arg1);
}

export function PruneRunDir(arg1, arg2) {
  return window['go']['main']['App']['PruneRunDir'](arg1, arg2);
}

export function ReplaceAllQueries(arg1) {
  return window['go']['main']['App']['ReplaceAllQueries'](arg1);
}

export function RequestScreenAccess() {
  return window['go']['main']['App']['RequestScreenAccess']();
}

export function SaveConfig(arg1) {
  return window['go']['main']['App']['SaveConfig'](arg1);
}

export function SaveQuery(arg1) {
  return window['go']['main']['App']['SaveQuery'](arg1);
}

export function SelectFile(arg1) {
  return window['go']['main']['App']['SelectFile'](arg1);
}

export function SelectOutputDir() {
  return window['go']['main']['App']['SelectOutputDir']();
}

export function SetSessionPassword(arg1, arg2) {
  return window['go']['main']['App']['SetSessionPassword'](arg1, arg2);
}

export function StartRun(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartRun'](arg1, arg2, arg3);
}

export function TestConnection(arg1) {
  return window['go']['main']['App']['TestConnection'](arg1);
}

export function UpdateTheme(arg1) {
  return window['go']['main']['App']['UpdateTheme'](arg1);
}
