// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {archive} from '../models';
import {store} from '../models';
import {main} from '../models';
import {config} from '../models';

export function ArchiveRun(arg1:string,arg2:string):Promise<archive.Result>;

export function ArchiveRunAuto(arg1:string):Promise<archive.Result>;

export function BringToFront():Promise<void>;

export function CancelRun():Promise<void>;

export function ClearSessionPasswords():Promise<void>;

export function DeleteQuery(arg1:string):Promise<Array<store.Query>>;

export function DetectEnvironment():Promise<main.EnvInfo>;

export function Emit(arg1:string,arg2:any):Promise<void>;

export function ExportQueries():Promise<string>;

export function GetConfig():Promise<config.Config>;

export function HasSessionPassword(arg1:string):Promise<boolean>;

export function ImportQueries(arg1:string):Promise<Array<store.Query>>;

export function IsRunning():Promise<boolean>;

export function ListQueries():Promise<Array<store.Query>>;

export function MoveQuery(arg1:string,arg2:number):Promise<Array<store.Query>>;

export function OpenRunFolder(arg1:string):Promise<void>;

export function PruneRunDir(arg1:string):Promise<void>;

export function ReplaceAllQueries(arg1:Array<store.Query>):Promise<Array<store.Query>>;

export function RequestScreenAccess():Promise<boolean>;

export function SaveConfig(arg1:config.Config):Promise<void>;

export function SaveQuery(arg1:store.Query):Promise<Array<store.Query>>;

export function SelectOutputDir():Promise<string>;

export function SetSessionPassword(arg1:string,arg2:string):Promise<void>;

export function StartRun():Promise<void>;

export function TestConnection(arg1:string):Promise<void>;
